### ISSUE TITLE
Don't use wildcards

### ISSUE THREAD

**Issue by fossfreedom** [ubuntucinnamonremix/ubuntucinnamon-meta#1]
In several of the files you have used the * wild-card

Don't do that since it will not build - and even if it did - will pull in debug and symbol files hence bloat your ISO generation.

I did a build on eoan and got the error message

`dpkg-gencontrol: warning: can't parse dependency atril-*
dpkg-gencontrol: error: error occurred while parsing Depends field: , acpi-support, adduser, alsa-base, alsa-utils, anacron, apt, apt-utils, at-spi2-core, atril-*, avahi-autoipd, avahi-daemon, bash-completion, bc, bluez, bluez-cups, brltty, bzip2, ca-certificates, cinnamon-*, console-setup, cups, cups-bsd, cups-client, cups-filters, debconf, debconf-i18n, doc-base, eject, eom-*, fonts-arphic-ukai, fonts-arphic-uming, fonts-dejavu-core, fonts-kacst-one, fonts-noto-cjk, fonts-sil-padauk, fonts-ubuntu, foomatic-db-compressed-ppds, genisoimage, ghostscript-x, gnome-menus, gnome-mpv-*, gstreamer1.0-alsa, gstreamer1.0-packagekit, gstreamer1.0-plugins-base-apps, gstreamer1.0-pulseaudio, gthumb-*, gtk-im-libthai, gvfs-bin, gvfs-fuse, hplip, htop, hunspell-en-au, hunspell-en-ca, hunspell-en-gb, hunspell-en-us, hunspell-en-za, ibus, ibus-chewing, ibus-gtk, ibus-gtk3, ibus-hangul, ibus-libpinyin, ibus-m17n, ibus-mozc, ibus-table, ibus-table-cangjie, ibus-table-quick-classic, ibus-table-wubi, ibus-unikey, im-config, init, initramfs-tools, inputattach, iproute2, iputils-ping, isc-dhcp-client, kbd, kerneloops, kimmo-*, kimmo-gtk-theme, kimmo-icon-theme, kmod, language-pack-en, language-pack-gnome-en, laptop-detect, less, libatk-adaptor, libgail-common, libnotify-bin, libnss-mdns, libpam-gnome-keyring, libproxy1-plugin-gsettings, libproxy1-plugin-networkmanager, libsasl2-modules, libu2f-udev, libwmf0.2-7-gtk, lightdm-*, locales, lsb-release, mawk, mount, mousetweaks, nano, net-tools, netbase, netcat-openbsd, netplan.io, network-manager, network-manager-config-connectivity-ubuntu, network-manager-pptp-gnome, nplan, openprinting-ppds, orca, p7zip-full, packagekit, passwd, pcmciautils, pluma-*, plymouth-theme-ubuntu-logo, plymouth-theme-ubuntu-text, policykit-desktop-privileges, printer-driver-brlaser, printer-driver-c2esp, printer-driver-foo2zjs, printer-driver-m2300w, printer-driver-min12xxw, printer-driver-pnm2ppa, printer-driver-ptouch, printer-driver-pxljr, printer-driver-sag-gdi, printer-driver-splix, procps, pulseaudio, pulseaudio-module-bluetooth, python3, resolvconf, rfkill, rsync, rsyslog, sensible-utils, slick-greeter-*, software-properties-gtk, speech-dispatcher, spice-vdagent, sudo, tzdata, ubuntu-advantage-tools, ubuntu-drivers-common, ubuntu-keyring, ubuntu-minimal, ubuntucinnamon-artwork, udev, unzip, vim-tiny, wamerican, wbritish, whiptail, wireless-tools, wpasupplicant, xcursor-themes, xdg-user-dirs, xdg-user-dirs-gtk, xdg-utils, xkb-data, xorg, zenity, zip
`

I can see lots of wild-cards there.

They have to be specific package names that you would normally use via `sudo apt install xyz`

**Comment by ubuntucinnamonremix** [comment]
Is this for all packages or just some, specifically pluma, eom, gnome-mpv, gthumb, and atril?

**Comment by fossfreedom** [comment]
All packages . Never use wildcards

**Comment by ubuntucinnamonremix** [comment]
Fixed.

**Comment by fossfreedom** [comment]
Does the package now build successfully?
