### ISSUE TITLE
desktop.list.chroot_live packages should not exist in desktop/desktop-recommends

### ISSUE THREAD

**Issue by fossfreedom** [ubuntucinnamonremix/ubuntucinnamon-meta#16]
Recent commits have added packages into chroot_live.

This is wrong - live are packages in addition to desktop and desktop-recommends.

**Comment by JPeisach** [comment]
I searched the whole repo and the only packages were none. Check again please, if there is show me specifically which one

**Comment by fossfreedom** [comment]
ubuntucinnamon-wallpapers
ubuntucinnamon-environment
kimmo-gtk-theme
kimmo-icon-theme
