### ISSUE TITLE
Missing live packages

### ISSUE THREAD

**Issue by fossfreedom** [ubuntucinnamonremix/ubuntucinnamon-meta#2]
Looks like the project does need the live meta package.

So need to readd the live files, modify the meta map file, debian/control file

The live package will have the chroot_live files ...

**Comment by ubuntucinnamonremix** [comment]
metamap file doesn't mention anything about the live, nor does debian/control.

**Comment by fossfreedom** [comment]
dunno why this was closed.  Live is still missing the stuff above.
