### ISSUE TITLE
ubuntucinnamon-desktop should rely on the other two packages

### ISSUE THREAD

**Issue by nardholio** [ubuntucinnamonremix/ubuntucinnamon-meta#24]
I migrated to Remix from a standard Ubuntu base. In order to ensure all the needed packages are installed, the Desktop version should rely on the Standard and CLI packages since it, by itself, doesn't ensure all the dependencies are there.

**Comment by JPeisach** [comment]
Thanks for being out first user issuer!

The “desktop” is the dependencies-just the desktop. The recommends has things like that.

Check if it is in desktop-recommends and if it is close the issue. -ItzSwirlz

**Comment by nardholio** [comment]
I'm talking about basic packages like "apt". Which are dependencies of the minimal package but not the desktop package.

**Comment by ubuntucinnamonremix** [comment]
A meta package as a recommend for a meta package is well... not a good idea.

But for important packages it needs to be added, so we will work.

**Comment by nardholio** [comment]
I see now you've just copied what ubuntu minimal and ubuntu desktop are doing. I find it strange since there's no guarantee someone would have both installed unless it's a dependency
